### ISSUE TITLE
[keyword] 3장 모든 객체의 공통 메서드

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/effective-java#18]
## 주제

`3장 모든 객체의 공통 메서드`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터
#17

**Comment by binchoo** [comment]
## 10. equals 메서드

### equals 메서드의 규약
1.  `x.equals(x)` (반사성)
2. `x.equals(y) = y.equals(x)` (대칭성)
3. `x.equals(y) = y.equals(z) then x.equals(z)` (추이성)
4. `x.equals(y) at t1 = x.equals(y) t2 where t1 <> t2` (일관성)
5. `x.equals(null) = false` (null-아님)

### equals 메서드를 정의해야 할 때
```
equals는 서로 다른 두 객체의 '논리적 일치'를 판단하고 싶을 때. eg. 값 객체
동시에, 그 기능을 위한 equals가 상위 타입에 없을 경우에 정의한다.
```

### 구체적인 클래스를 확장하고 새 필드를 추가하면서 equals 규약을 만족시킬 방법은 없다.
- 리스코프 치환 원칙, 대칭성, 추이성 위반이 필연적이다.
- 대안: 상속 대신 컴포지션하라.
```java
public class ColorPoint {
  private final Point p;
  private final Color color;
  public ColorPoint(Point p, Color color) { ... }
  public Point asPoint() { return point; }
  @Override public boolean equals(Object o) {
    if (o instanceof ColorPoint) {
      ColorPoint cp = (ColorPoint) o;
      return cp.point.equals(point) && cp.color.equals(color);
    }
    return false;
  }
}
```

### 잘못 구현된 클래스들
- java.util.Date <- java.sql.Timestamp (대칭성, 추이성 위반)
- java.net.URL (일관성 위반)

### equals 구현 가이드라인
- hashCode도 재정의한다.
- `==`으로 자기 자신임을 확인한다.
- `instanceof`로 동일한 타입인지 확인한다. **그럼 null 검사는 필요없다**.
- 핵심 필드들을 비교한다.
  - 비용의 싼 필드부터 비교한다.
  - 필드 고유의 equals를 사용한다. (Map, Map.Entry, Set, List, Arrays)
  - 부동소수점의 경우 `Float.compareTo(), Double.compareTo()`를

**Comment by binchoo** [comment]
## HashMap, TreeMap
"Key의 중복은 허용하지 않는다"

"Hash가 중복되면"
1. LinkedList
2. Universal Hashing 

## HashSet, TreeSet
HashMap, TreeMap으로 구현
## MultiValueMap
"key" -> LinkedList
