### ISSUE TITLE
[keyword] 11장 - 동시성

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/effective-java#41]
## 주제

'11장 - 동시성'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

**Comment by JasonYoo1995** [comment]
- spring에서 공유 변수를 사용하는 사례가 종종 있을까? : https://www.e4developer.com/2018/03/30/introduction-to-concurrency-in-spring-boot/
- volatile : https://www.baeldung.com/java-volatile-variables-thread-safety

**Comment by ngwoon** [comment]
책에서 소개한 "가변 클래스 작성 시 동시성 고려 방법"
1. 동기화 하지 말고, 클라이언트 코드에서 동기화 하게 둔다. (물론 설명에는 thread-unsafe 추가해 두어야 함)
2. 완벽하게 동기화 해둔다.

이 중 2번을 이루기 위해 세 가지 방식을 언급하고 있다.
* 락 분할 = 기능 별로 다른 lock 객체를 사용하는 방법 (ex. 파일 읽기/쓰기 메서드 별로 다른 lock 객체 사용)
* 락 스트라이핑 = 부분 별로 다른 lock 객체를 사용하는 방법 (ex. ConcurrentHashMap)
* 비차단 동시성 제어 (ex. Atomic)
