### ISSUE TITLE
[question] 계층형 빌더

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/effective-java#6]
## 질문
책 p.19의 예제에서 Pizza class를 구성할 때, 계층형 Builder를 구현하고 있습니다.
제네릭에 익숙하지 않아 해당 코드를 이해할 때 어려움이 조금 있었는데, 함께 읽으면서 이해하면 좋을 것 같네요 😄 

## 연관 챕터
#1

**Comment by binchoo** [comment]
저자는, 
하위 클래스의 빌더들이 
부모인 `Pizza.Builder`의 수정자들을 재사용 하도록 설계했습니다.

수정자 메서드 맨 마지막에 
추상 메서드 `self()`를 박아 넣고, 자손들이 이 지점을 확장하도록 했는데요.

빌더 패턴의 UX인 메서드 체이닝을 보장하기 위해서는
그들은 자기 자신을 반환할 것이 **MUST** 보장되어야 합니다. (핵심)

```java
T addTopping(Topping topping) {
  toppings.add(Objects.requireNonNull(topping));
  return self(); // 템플릿 메서드
}
```

```java
// Pizza에서
abstract T self();

// NyPizza에서
@Override 
public NyPizza.Builder self() {
  return this;
}
```

`Pizza`에서 제네릭 `T extends Builder<T>`를 소개한 이유를 살펴 봅시다.

1. 일단 `self()`의 반환이 Pizza.Builder, NyPizza.Builder, 다른자손.Builder가 될 수 있어서 결정된 사항이 없습니다. 따라서 제네릭 `T`가 자명히 소개되어야 하고.
```java
abstract static class Builder<T> {
}
```
2. 이때 T에 아무나 대치되도록 하면 멍청한 API 이용자가 다음과 같은 만행을 저지를 수 있습니다.
```java
Pizza.Builder myBuilder = new Pizza.Builder<String>() {
  @Override 
  public String self() { return "foobar";}
}
```
3. 그래서 `self()`가 자손 빌더만을 반환하도록 제어하려면, `T`에 제약조건을 붙입니다. Pizza.Builder의 자손이기 때문에 직관적으로 `T extends Builder<?>`를 소개하게 됩니다.
```java
abstract static class Builder<T extends Builder<?>> { 
}
// NyPizza 문제 없음.
static class Builder extends Pizza.Builder<Builder> { 
  @Override
  public Builder self() { ... };
}
```
본인 생각으로 `T extends Builder<?>`로 무방하다고 생각되는데요, 뒤에서 재귀 제네릭 타입 (아이템30)을 설명한다고 하니 기대해 보죠.

4. 3번과 `T extends Builder<T>`를 엄밀히 비교하려면, T위치에 `MyBuilder`라고 대치해 보세요. 후자가 더 좁은 바운드를 갖습니다. 다만 뭘 써도 `MyBuilder`를 변수로 받아내는데 지장은 없어 보입니다.
```java
MyBuilder extends Builder<?> // 맞는말
MyBuilder extends Builder<MyBuilder> // 맞는말
```
